Algoritmo "semnome"



Var
 idade: inteiro
 salario1,salario2 : real
 nome: caractere
 
   

Inicio

 escreva ("Digite seu nome:")
 Leia (nome)
 escreva ("Digite sua idade:")
 Leia (idade)
 escreval ("Seus dois ultimos salarios:")
 Leia(salario1)
 Leia(salario2)
 
 escreval ("Dados Digitados:")
 escreval ("Nome:", nome)
 escreval ("idade:", idade)
 escreval ("Salario:", salario1)
 escreval ("Salario:", salario2)
 
 


Fimalgoritmo